### ISSUE TITLE
status

### ISSUE THREAD

**Issue by jlozadad** [kairoaraujo/ansible-aix-support#3]
hello, are you still planning on submitting this to ansible core?

**Comment by kairoaraujo** [comment]
Hi @jlozadad , sorry my late reply. 

I have been very busy with many changes.
Yes, I still planning to submit all these modules to Ansible core. I already submitted the PR  https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Akairoaraujo+archived%3Afalse+ansible 

I will back to work on review requests to have it merged to the core.
