### ISSUE TITLE
edit aix stanza files 

### ISSUE THREAD

**Issue by flynn1973** [kairoaraujo/ansible-aix-support#5]
it seems you are quite deep into aix and ansible. any idea how to edit aix stanza files with ansible? blockinfile/lineinfile are not the best for this task.

**Comment by k3it** [comment]
many aix stanza files have a user space program for editing or adding entries
e.g. chsec, chfs..
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.cmds1/chsec.htm

in many cases it's safer to use one of these supplied tools instead of direct edits

**Comment by kairoaraujo** [comment]
I see on Ansible Developer list that there is someone working on it. 

https://groups.google.com/forum/m/#!topic/ansible-devel/d1DTNAM8JiA

I will try to help him this week but I don’t have AIX environment at the moment and I will keep updated here

**Comment by flynn1973** [comment]
This is my posting, so yes, your help is very welcome.

________________________________­­­
Christian Tremel
IT-Services der Sozialversicherung GmbH

Rechenzentrum
AIX Systemadministrator
Gruberstraße 77
A – 4021 Linz
T: +43 (0)50124 844 1266
M: +43 (0)664 88661266
christian.tremel@itsv.at<mailto:christian.tremel@itsv.at>
www.itsv.at<http://www.itsv.at>

[https://plattform.sozvers.at/Lists/Schlagzeilen/Attachments/493/CIS-Logo-Signatur.png]


Von: Kairo Araujo [mailto:notifications@github.com]
Gesendet: Montag, 19. November 2018 07:54
An: kairoaraujo/ansible-aix-support <ansible-aix-support@noreply.github.com>
Cc: Tremel Christian <Christian.Tremel@itsv.at>; Author <author@noreply.github.com>
Betreff: Re: [kairoaraujo/ansible-aix-support] edit aix stanza files (#5)


I see on Ansible Developer list that there is someone working on it.

https://groups.google.com/forum/m/#!topic/ansible-devel/d1DTNAM8JiA

I will try to help him this week but I don’t have AIX environment at the moment and I will keep updated here

**Comment by kairoaraujo** [comment]
Hi @flynn1973 great job.
Today and following days I will try to have a AIX LPAR to help you.
Feel free to do a PR here also on ansible-aix-support repository, will even easy to help you having the PR updated.
I also suggest do it on Ansible official project, sometime it takes long but is good for the project.

**Comment by flynn1973** [comment]
Thats the plan anyway, this  module should go right in your repo.  Beside this, you can test this module on a linux lpar, so no absolute need for an aix machine.

Repo with code and example playbook:

https://github.com/flynn1973/ansible_aix_stanza



________________________________­­­
Christian Tremel
IT-Services der Sozialversicherung GmbH

Rechenzentrum
AIX Systemadministrator
Gruberstraße 77
A – 4021 Linz
T: +43 (0)50124 844 1266
M: +43 (0)664 88661266
christian.tremel@itsv.at<mailto:christian.tremel@itsv.at>
www.itsv.at<http://www.itsv.at>

[https://plattform.sozvers.at/Lists/Schlagzeilen/Attachments/493/CIS-Logo-Signatur.png]


Von: Kairo Araujo [mailto:notifications@github.com]
Gesendet: Montag, 19. November 2018 09:22
An: kairoaraujo/ansible-aix-support <ansible-aix-support@noreply.github.com>
Cc: Tremel Christian <Christian.Tremel@itsv.at>; Mention <mention@noreply.github.com>
Betreff: Re: [kairoaraujo/ansible-aix-support] edit aix stanza files (#5)


Hi @flynn1973<https://github.com/flynn1973> great job.
Today and following days I will try to have a AIX LPAR to help you.
Feel free to do a PR here also on ansible-aix-support repository, will even easy to help you having the PR updated.
I also suggest do it on Ansible official project, sometime it takes long but is good for the project.

**Comment by flynn1973** [comment]
not relevant anymore...closing
